package AnsweringAPP.dados

import android.content.Context
import com.AnsweringAPP.R

class Questions(ctx: Context) {
    var Basic = arrayOf<List<String>>(
        listOf<String>(ctx.getString(R.string.question1), ctx.getString(R.string.hint1)),
        listOf<String>(ctx.getString(R.string.question2), ctx.getString(R.string.hint2)),
        listOf<String>(ctx.getString(R.string.question3), ctx.getString(R.string.hint3)),
        listOf<String>(ctx.getString(R.string.question4), ctx.getString(R.string.hint4)),
        listOf<String>(ctx.getString(R.string.question5), ctx.getString(R.string.hint5)),
        listOf<String>(ctx.getString(R.string.question6), ctx.getString(R.string.hint6)),
        listOf<String>(ctx.getString(R.string.question7), ctx.getString(R.string.hint7)),
        listOf<String>(ctx.getString(R.string.question8), ctx.getString(R.string.hint8)),
        listOf<String>(ctx.getString(R.string.question9), ctx.getString(R.string.hint9)),
        listOf<String>(ctx.getString(R.string.question11), ctx.getString(R.string.hint11)),
        listOf<String>(ctx.getString(R.string.question12), ctx.getString(R.string.hint12)),
        listOf<String>(ctx.getString(R.string.question13), ctx.getString(R.string.hint13)),
        listOf<String>(ctx.getString(R.string.question14), ctx.getString(R.string.hint14)),
        listOf<String>(ctx.getString(R.string.question15), ctx.getString(R.string.hint15)),
        listOf<String>(ctx.getString(R.string.question16), ctx.getString(R.string.hint16)),
        listOf<String>(ctx.getString(R.string.question17), ctx.getString(R.string.hint17)),
        listOf<String>(ctx.getString(R.string.question18), ctx.getString(R.string.hint18)),
        listOf<String>(ctx.getString(R.string.question19), ctx.getString(R.string.hint19)),
        listOf<String>(ctx.getString(R.string.question20), ctx.getString(R.string.hint20)),
        listOf<String>(ctx.getString(R.string.question21), ctx.getString(R.string.hint21)),
        listOf<String>(ctx.getString(R.string.question22), ctx.getString(R.string.hint22)),
        listOf<String>(ctx.getString(R.string.question23), ctx.getString(R.string.hint23)),
        listOf<String>(ctx.getString(R.string.question24), ctx.getString(R.string.hint24)),
        listOf<String>(ctx.getString(R.string.question25), ctx.getString(R.string.hint25)),
        listOf<String>(ctx.getString(R.string.question26), ctx.getString(R.string.hint26)),
        listOf<String>(ctx.getString(R.string.question27), ctx.getString(R.string.hint27)),
        listOf<String>(ctx.getString(R.string.question28), ctx.getString(R.string.hint28)),
        listOf<String>(ctx.getString(R.string.question29), ctx.getString(R.string.hint29)),
        listOf<String>(ctx.getString(R.string.question30), ctx.getString(R.string.hint30)),
        listOf<String>(ctx.getString(R.string.question31), ctx.getString(R.string.hint31)),
        listOf<String>(ctx.getString(R.string.question32), ctx.getString(R.string.hint32)),
        listOf<String>(ctx.getString(R.string.question33), ctx.getString(R.string.hint33)),
        listOf<String>(ctx.getString(R.string.question34), ctx.getString(R.string.hint34)),
        listOf<String>(ctx.getString(R.string.question35), ctx.getString(R.string.hint35)),
        listOf<String>(ctx.getString(R.string.question36), ctx.getString(R.string.hint36)),
        listOf<String>(ctx.getString(R.string.question37), ctx.getString(R.string.hint37)),
        listOf<String>(ctx.getString(R.string.question38), ctx.getString(R.string.hint38))

        )

    var Intermediate = arrayOf<List<String>>(
        listOf<String>(ctx.getString(R.string.qinterm1), ctx.getString(R.string.hinterm1)),
        listOf<String>(ctx.getString(R.string.qinterm2), ctx.getString(R.string.hinterm2)),
        listOf<String>(ctx.getString(R.string.qinterm3), ctx.getString(R.string.hinterm3)),
        listOf<String>(ctx.getString(R.string.qinterm4), ctx.getString(R.string.hinterm4)),
        listOf<String>(ctx.getString(R.string.qinterm5), ctx.getString(R.string.hinterm5)),
        listOf<String>(ctx.getString(R.string.qinterm6), ctx.getString(R.string.hinterm6)),
        listOf<String>(ctx.getString(R.string.qinterm7), ctx.getString(R.string.hinterm7)),
        listOf<String>(ctx.getString(R.string.qinterm8), ctx.getString(R.string.hinterm8)),
        listOf<String>(ctx.getString(R.string.qinterm9), ctx.getString(R.string.hinterm9)),
        listOf<String>(ctx.getString(R.string.qinterm11), ctx.getString(R.string.hinterm11)),
        listOf<String>(ctx.getString(R.string.qinterm12), ctx.getString(R.string.hinterm12)),
        listOf<String>(ctx.getString(R.string.qinterm13), ctx.getString(R.string.hinterm13)),
        listOf<String>(ctx.getString(R.string.qinterm14), ctx.getString(R.string.hinterm14)),
        listOf<String>(ctx.getString(R.string.qinterm15), ctx.getString(R.string.hinterm15)),
        listOf<String>(ctx.getString(R.string.qinterm16), ctx.getString(R.string.hinterm16)),
        listOf<String>(ctx.getString(R.string.qinterm17), ctx.getString(R.string.hinterm17)),
        listOf<String>(ctx.getString(R.string.qinterm18), ctx.getString(R.string.hinterm18)),
        listOf<String>(ctx.getString(R.string.qinterm19), ctx.getString(R.string.hinterm19)),
        listOf<String>(ctx.getString(R.string.qinterm20), ctx.getString(R.string.hinterm20)),
        listOf<String>(ctx.getString(R.string.qinterm21), ctx.getString(R.string.hinterm21)),
        listOf<String>(ctx.getString(R.string.qinterm22), ctx.getString(R.string.hinterm22)),
        listOf<String>(ctx.getString(R.string.qinterm23), ctx.getString(R.string.hinterm23)),
        listOf<String>(ctx.getString(R.string.qinterm24), ctx.getString(R.string.hinterm24)),
        listOf<String>(ctx.getString(R.string.qinterm25), ctx.getString(R.string.hinterm25)),
        listOf<String>(ctx.getString(R.string.qinterm26), ctx.getString(R.string.hinterm26)),
        listOf<String>(ctx.getString(R.string.qinterm27), ctx.getString(R.string.hinterm27)),
        listOf<String>(ctx.getString(R.string.qinterm28), ctx.getString(R.string.hinterm28)),
        listOf<String>(ctx.getString(R.string.qinterm29), ctx.getString(R.string.hinterm29)),
        listOf<String>(ctx.getString(R.string.qinterm30), ctx.getString(R.string.hinterm30)),
        listOf<String>(ctx.getString(R.string.qinterm31), ctx.getString(R.string.hinterm31)),
        listOf<String>(ctx.getString(R.string.qinterm32), ctx.getString(R.string.hinterm32)),
        listOf<String>(ctx.getString(R.string.qinterm33), ctx.getString(R.string.hinterm33)),
        listOf<String>(ctx.getString(R.string.qinterm34), ctx.getString(R.string.hinterm34)),
        listOf<String>(ctx.getString(R.string.qinterm35), ctx.getString(R.string.hinterm35)),
        listOf<String>(ctx.getString(R.string.qinterm36), ctx.getString(R.string.hinterm36)),
        listOf<String>(ctx.getString(R.string.qinterm37), ctx.getString(R.string.hinterm37)),
        listOf<String>(ctx.getString(R.string.qinterm38), ctx.getString(R.string.hinterm38)),
        listOf<String>(ctx.getString(R.string.qinterm39), ctx.getString(R.string.hinterm39)),
        listOf<String>(ctx.getString(R.string.qinterm40), ctx.getString(R.string.hinterm40)),
        listOf<String>(ctx.getString(R.string.qinterm41), ctx.getString(R.string.hinterm41)),
        listOf<String>(ctx.getString(R.string.qinterm42), ctx.getString(R.string.hinterm42)),
        listOf<String>(ctx.getString(R.string.qinterm43), ctx.getString(R.string.hinterm43)),
        listOf<String>(ctx.getString(R.string.qinterm44), ctx.getString(R.string.hinterm44)),
        listOf<String>(ctx.getString(R.string.qinterm45), ctx.getString(R.string.hinterm45)),


    )

    var Advanced = arrayOf<List<String>>(
        listOf<String>(ctx.getString(R.string.qadvanc1), ctx.getString(R.string.hadvanc1)),
        listOf<String>(ctx.getString(R.string.qadvanc2), ctx.getString(R.string.hadvanc2)),
        listOf<String>(ctx.getString(R.string.qadvanc3), ctx.getString(R.string.hadvanc3)),
        listOf<String>(ctx.getString(R.string.qadvanc4), ctx.getString(R.string.hadvanc4)),
        listOf<String>(ctx.getString(R.string.qadvanc5), ctx.getString(R.string.hadvanc5)),
        listOf<String>(ctx.getString(R.string.qadvanc6), ctx.getString(R.string.hadvanc6)),
        listOf<String>(ctx.getString(R.string.qadvanc7), ctx.getString(R.string.hadvanc7)),
        listOf<String>(ctx.getString(R.string.qadvanc8), ctx.getString(R.string.hadvanc8)),
        listOf<String>(ctx.getString(R.string.qadvanc9), ctx.getString(R.string.hadvanc9)),
        listOf<String>(ctx.getString(R.string.qadvanc10), ctx.getString(R.string.hadvanc10)),
        listOf<String>(ctx.getString(R.string.qadvanc11), ctx.getString(R.string.hadvanc11)),
        listOf<String>(ctx.getString(R.string.qadvanc12), ctx.getString(R.string.hadvanc12)),
        listOf<String>(ctx.getString(R.string.qadvanc13), ctx.getString(R.string.hadvanc13)),
        listOf<String>(ctx.getString(R.string.qadvanc14), ctx.getString(R.string.hadvanc14)),
        listOf<String>(ctx.getString(R.string.qadvanc15), ctx.getString(R.string.hadvanc15)),
        listOf<String>(ctx.getString(R.string.qadvanc16), ctx.getString(R.string.hadvanc16)),
        listOf<String>(ctx.getString(R.string.qadvanc17), ctx.getString(R.string.hadvanc17)),
        listOf<String>(ctx.getString(R.string.qadvanc18), ctx.getString(R.string.hadvanc18)),
        listOf<String>(ctx.getString(R.string.qadvanc19), ctx.getString(R.string.hadvanc19)),
        listOf<String>(ctx.getString(R.string.qadvanc20), ctx.getString(R.string.hadvanc20)),
        listOf<String>(ctx.getString(R.string.qadvanc21), ctx.getString(R.string.hadvanc21)),
        listOf<String>(ctx.getString(R.string.qadvanc22), ctx.getString(R.string.hadvanc22)),
        listOf<String>(ctx.getString(R.string.qadvanc23), ctx.getString(R.string.hadvanc23)),
        listOf<String>(ctx.getString(R.string.qadvanc24), ctx.getString(R.string.hadvanc24)),
        listOf<String>(ctx.getString(R.string.qadvanc25), ctx.getString(R.string.hadvanc25)),
        listOf<String>(ctx.getString(R.string.qadvanc26), ctx.getString(R.string.hadvanc26)),
        listOf<String>(ctx.getString(R.string.qadvanc27), ctx.getString(R.string.hadvanc27)),
        listOf<String>(ctx.getString(R.string.qadvanc28), ctx.getString(R.string.hadvanc28)),
        listOf<String>(ctx.getString(R.string.qadvanc29), ctx.getString(R.string.hadvanc29)),
        listOf<String>(ctx.getString(R.string.qadvanc30), ctx.getString(R.string.hadvanc30)),
        listOf<String>(ctx.getString(R.string.qadvanc31), ctx.getString(R.string.hadvanc31)),
        listOf<String>(ctx.getString(R.string.qadvanc32), ctx.getString(R.string.hadvanc32)),
        listOf<String>(ctx.getString(R.string.qadvanc33), ctx.getString(R.string.hadvanc33)),
        listOf<String>(ctx.getString(R.string.qadvanc34), ctx.getString(R.string.hadvanc34)),
        listOf<String>(ctx.getString(R.string.qadvanc35), ctx.getString(R.string.hadvanc35)),
        listOf<String>(ctx.getString(R.string.qadvanc36), ctx.getString(R.string.hadvanc36)),
        listOf<String>(ctx.getString(R.string.qadvanc37), ctx.getString(R.string.hadvanc37)),
        listOf<String>(ctx.getString(R.string.qadvanc38), ctx.getString(R.string.hadvanc38)),
        listOf<String>(ctx.getString(R.string.qadvanc39), ctx.getString(R.string.hadvanc39)),
        listOf<String>(ctx.getString(R.string.qadvanc40), ctx.getString(R.string.hadvanc40))
        )
    var begInterm : Array<List<String>> = (Basic + Intermediate)
    var allLevels : Array<List<String>> = (Basic + Intermediate + Advanced)




}